"""
workflow.py

Central workflow orchestration for StatVerify AI.

The workflow is intentionally independent from Streamlit.

UI  ---> Workflow ---> Parser ---> Statistics ---> Reports ---> AI

Pipeline (matching the documented workflow diagram):

  START
    ↓
  parse       ← Parser: Load + Clean + Schema Detection
    ↓
  validate    ← Validator: Missing / Invalid / Data Quality Checks
    ↓
  context     ← Planner: Identify dependent / independent / group variables
    ↓
  extract     ← Extractor: Build statistical dataset
    ↓
  select_test ← Decision Engine: Select appropriate statistical test
    ↓
  statistics  ← Statistical Engine: Execute calculation using SciPy
    ↓          ↓
  verify      explain   ← Parallel branches (Verification + AI Explanation)
     ↓          ↓
     └────┬─────┘
          ↓
        report      ← Report Builder: Statistics + Verification + AI
          ↓
        PDF Report

The workflow communicates through a shared state object.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, TypedDict

from langgraph.graph import END, START, StateGraph

from src.models import (
    AnalysisMode,
    AnalysisRequest,
    InputType,
    ReportData,
    StatisticalResult,
    StatisticalTest,
)
from src.parser import UniversalParser
from src.planner import AnalysisPlanner
from src.extractor import StatisticalDataExtractor
from src.statistics import StatisticalDecisionEngine, StatisticalEngine
from src.utils import logger
from src.validator import DataValidator


# ==========================================================
# Workflow State
# ==========================================================


class WorkflowState(TypedDict):
    """
    Shared workflow state.

    Fields written by parallel branches (verify + explain) use
    Annotated[..., operator.add] reducers so LangGraph can merge
    concurrent writes without raising InvalidUpdateError.

    All other fields are written by a single node and use plain types.
    """

    request: Any

    selected_test: Any

    parsed_table: Any

    context: Any

    dataset: Any

    test_recommendation: Any

    statistical_result: Any

    # Only used in verification mode
    reported_result: Any

    # Written by verify branch — use last-write-wins via a list reducer
    verification_result: Any

    report: Any

    # Written by explain branch
    ai_response: Any

    # PDF generated by ReportEngine
    report_path: str | None

    # Raw PDF bytes for Streamlit download_button
    report_pdf: bytes | None

    error: str | None

    group_size_override: dict | None


# ==========================================================
# Orchestrator Components
# ==========================================================

parser = UniversalParser()

validator = DataValidator()

planner = AnalysisPlanner()

extractor = StatisticalDataExtractor()

decision_engine = StatisticalDecisionEngine()

statistics_engine = StatisticalEngine()

from src.verification import VerificationEngine
from src.ai import AIEngine
from src.reports import ReportEngine

verification_engine = VerificationEngine()

report_engine = ReportEngine()

ai_engine = AIEngine()


# ==========================================================
# Helpers
# ==========================================================


def has_error(state: WorkflowState) -> bool:
    """
    Stop executing workflow if any previous stage failed.
    """

    return state.get("error") is not None


# ==========================================================
# Workflow Nodes
# ==========================================================


def parse_input(state: WorkflowState) -> WorkflowState:
    """
    Parse uploaded input.

    Workflow Stage: Parser
    Responsibilities: Load + Clean + Schema Detection
    """
    if has_error(state):
        return state

    try:
        logger.info("Running parser...")

        input_data = state.get("request") or "sample.csv"
        if isinstance(input_data, AnalysisRequest) and input_data.source_name:
            input_data = input_data.source_name
        elif hasattr(input_data, "source"):
            input_data = input_data.source

        state["parsed_table"] = parser.parse(input_data)

        # If the UI provided explicit group sizes (user was prompted
        # because N= wasn't in the headers), inject them into
        # summary_metadata so the extractor picks them up.
        override = state.get("group_size_override")
        if override and state["parsed_table"] is not None:
            sm = state["parsed_table"].summary_metadata
            if "_sample_sizes" not in sm or not sm["_sample_sizes"]:
                sm["_sample_sizes"] = override

        logger.info("Parser completed successfully.")

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def validate_data(state: WorkflowState) -> WorkflowState:
    """
    Validate parsed table.

    Workflow Stage: Validator
    Responsibilities: Missing / Invalid / Data Quality Checks
    """
    if has_error(state):
        return state

    try:
        logger.info("Validating data...")

        table = state.get("parsed_table")
        if table is not None:
            validation = validator.validate(table)
            table.validation = validation

            # Log validation summary
            errors = [m for m in validation.messages if m.severity.value == "error"]
            warnings = [m for m in validation.messages if m.severity.value == "warning"]
            logger.info(
                f"Validation complete: {len(errors)} error(s), {len(warnings)} warning(s)."
            )

            if errors:
                # Surface first error message to state
                state["error"] = errors[0].message

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def build_context(state: WorkflowState) -> WorkflowState:
    """
    Build statistical context.

    Workflow Stage: Planner
    Responsibilities: Identify dependent / independent / group variables
    """
    if has_error(state):
        return state

    try:
        logger.info("Building analysis context (planner)...")

        table = state["parsed_table"]

        context = planner.build_context(table)
        state["context"] = context

        logger.info(
            f"Context built: dependent={context.dependent_variable}, "
            f"independent={context.independent_variable}, "
            f"group={context.group_variable}"
        )

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def extract_dataset(state: WorkflowState) -> WorkflowState:
    """
    Extract statistical dataset from parsed table and context.

    Workflow Stage: Extractor
    Responsibilities: Build statistical dataset
    """
    if has_error(state):
        return state

    try:
        logger.info("Extracting dataset...")

        table = state.get("parsed_table")
        request = state.get("request")

        role_mapping = getattr(request, "role_mapping", None)

        if table is not None and role_mapping is not None:
            state["dataset"] = extractor.extract_with_role_mapping(
                table,
                role_mapping,
            )
        elif table is not None and state.get("context") is not None:
            state["dataset"] = extractor.extract(
                table,
                state["context"],
            )

        dataset = state.get("dataset")
        if dataset is not None:
            logger.info(
                f"Dataset extracted: sample_size={dataset.sample_size}, "
                f"groups={list(dataset.groups.keys()) if dataset.groups else 'none'}, "
                f"is_summary={dataset.is_summary}"
            )

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def select_test(state: WorkflowState) -> WorkflowState:
    """
    Select statistical test.

    Workflow Stage: Decision Engine
    Responsibilities: Select appropriate statistical test

    If the user selected a test, use it.
    Otherwise, automatically recommend one.
    """
    if has_error(state):
        return state

    try:
        logger.info("Selecting statistical test (decision engine)...")

        selected = state.get("selected_test")
        request = state.get("request")

        if getattr(request, "role_mapping", None) is not None and selected is None:

            from src.models import TestRecommendation

            state["test_recommendation"] = TestRecommendation(
                test=StatisticalTest.CHI_SQUARE,
                reason="User-confirmed group-comparison summary table → Chi-Square.",
                confidence=1.0,
            )

            return state

        # User selected a test explicitly
        if selected is not None:

            from src.models import TestRecommendation

            state["test_recommendation"] = TestRecommendation(
                test=selected,
                reason="User selected statistical test.",
                confidence=1.0,
            )

            logger.info(f"User-selected test: {selected.value}")
            return state

        # Automatic recommendation
        table = state.get("parsed_table")
        context = state.get("context")

        if table is not None:
            recommendation = decision_engine.recommend(table, context)
            state["test_recommendation"] = recommendation
            logger.info(
                f"Recommended test: {recommendation.test.value} "
                f"(confidence={recommendation.confidence:.0%}). "
                f"Reason: {recommendation.reason}"
            )

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def run_statistics(state: WorkflowState) -> WorkflowState:
    """
    Execute statistical analysis.

    Workflow Stage: Statistical Engine
    Responsibilities: Execute calculation using SciPy
    """
    if has_error(state):
        return state

    try:
        logger.info("Running statistical engine...")

        dataset = state.get("dataset")
        recommendation = state.get("test_recommendation")

        if dataset is not None and recommendation is not None:
            result = statistics_engine.execute(dataset, recommendation)
            state["statistical_result"] = result

            logger.info(
                f"Statistics computed: test={result.test_name}, "
                f"statistic={result.statistic}, p_value={result.p_value}, "
                f"effect_size={result.effect_size}"
            )

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def verify_results(state: WorkflowState) -> dict:
    """
    Compare reported and calculated statistics.

    Workflow Stage: Verification
    Responsibilities: Compare reported vs calculated statistics

    Returns only {verification_result} to avoid parallel write conflicts.
    """
    if has_error(state):
        return {}

    logger.info("Running verification...")

    try:
        request = state.get("request")
        calculated = state.get("statistical_result")

        if calculated is None:
            logger.info("No statistical result available — skipping verification.")
            return {}

        if (
            request is not None
            and request.mode == AnalysisMode.VERIFICATION
        ):
            # Full verification: compare reported paper values vs calculated
            reported = state.get("reported_result")

            if reported is None:
                logger.info(
                    "Verification mode selected but no reported_result provided "
                    "— skipping comparison."
                )
                return {}

            vr = verification_engine.verify(reported, calculated)
            logger.info(f"Verification complete: verified={vr.verified}")
            return {"verification_result": vr}

        else:
            # Calculation mode: internal consistency check
            vr = _internal_consistency_check(calculated)
            logger.info(f"Internal consistency check: passed={vr.verified}")
            return {"verification_result": vr}

    except Exception as error:
        logger.exception(error)
        return {"error": str(error)}


def explain_results(state: WorkflowState) -> dict:
    """
    Generate AI explanation.

    Workflow Stage: AI Explanation
    Responsibilities: Explain result without performing calculations

    Returns only {ai_response} to avoid parallel write conflicts.
    """
    if has_error(state):
        return {}

    logger.info("Generating AI explanation...")

    try:
        result = state.get("statistical_result")
        if result is None:
            return {}

        ai = ai_engine.explain(result)
        return {"ai_response": ai}

    except Exception as error:
        logger.exception(error)
        return {"error": str(error)}


def generate_report(state: WorkflowState) -> WorkflowState:
    """
    Build report and generate PDF.

    Workflow Stage: Report Builder
    Responsibilities: Statistics + Verification + AI
    """
    if has_error(state):
        return state

    logger.info("Generating report...")

    try:

        req = state.get("request")

        if not isinstance(req, AnalysisRequest):
            req = AnalysisRequest(
                mode=AnalysisMode.CALCULATION,
                input_type=InputType.CSV,
                source_name="sample.csv",
            )

        stat = state.get("statistical_result")

        if stat is None:
            stat = StatisticalResult(test_name="Unknown")

        report = ReportData(
            request=req,
            statistics=stat,
            verification=state.get("verification_result"),
            ai=state.get("ai_response"),
        )

        state["report"] = report

        # --- Generate PDF and capture bytes ---
        pdf_path = report_engine.generate(report)
        state["report_path"] = str(pdf_path)

        with open(pdf_path, "rb") as fh:
            state["report_pdf"] = fh.read()

        logger.info("PDF generated: %s (%d bytes)", pdf_path, len(state["report_pdf"]))

    except Exception as error:

        logger.exception(error)

        state["error"] = str(error)

    return state


# ==========================================================
# Internal Consistency Check (Calculation Mode)
# ==========================================================


def _internal_consistency_check(result: StatisticalResult):
    """
    Perform a lightweight internal consistency check on a StatisticalResult.

    This runs in CALCULATION mode (no paper to compare against).
    It verifies:
    - p-value is in [0, 1]
    - statistic is a real number (if present)
    - effect_size is finite (if present)
    """
    from src.models import (
        ComparisonItem,
        ComparisonResult,
        VerificationResult,
    )
    import math

    checks: list[ComparisonItem] = []
    all_passed = True

    # p-value range check
    p = result.p_value
    if p is not None:
        in_range = 0.0 <= p <= 1.0
        checks.append(
            ComparisonItem(
                metric="p-value range [0, 1]",
                reported=p,
                calculated=p,
                matched=in_range,
                difference=None,
            )
        )
        if not in_range:
            all_passed = False

    # Statistic is finite
    s = result.statistic
    if s is not None:
        finite = math.isfinite(s)
        checks.append(
            ComparisonItem(
                metric="statistic is finite",
                reported=s,
                calculated=s,
                matched=finite,
                difference=None,
            )
        )
        if not finite:
            all_passed = False

    # Effect size is finite (if present)
    e = result.effect_size
    if e is not None:
        finite_e = math.isfinite(e)
        checks.append(
            ComparisonItem(
                metric="effect_size is finite",
                reported=e,
                calculated=e,
                matched=finite_e,
                difference=None,
            )
        )
        if not finite_e:
            all_passed = False

    # If no fields were present, report neutral pass
    if not checks:
        checks.append(
            ComparisonItem(
                metric="Result populated",
                reported=None,
                calculated=None,
                matched=True,
                difference=None,
            )
        )

    summary = (
        "Internal consistency checks passed."
        if all_passed
        else "One or more internal consistency checks failed."
    )

    comparison = ComparisonResult(
        passed=all_passed,
        items=checks,
        summary=summary,
    )

    return VerificationResult(
        verified=all_passed,
        comparison=comparison,
        reported_result=result,
        calculated_result=result,
        message=summary,
    )


# ==========================================================
# Build Workflow
# ==========================================================


def build_workflow():
    """
    Build LangGraph workflow.

    Topology (matches the workflow diagram):

    START → parse → validate → context → extract → select_test → statistics
                                                                        ↓        ↓
                                                                    verify   explain   (parallel)
                                                                        ↓        ↓
                                                                      report ←──◙
                                                                        ↓
                                                                      END

    LangGraph fan-out: statistics has two outgoing edges (verify and explain).
    Both run concurrently and both feed into report.
    Each branch writes to a disjoint set of state keys so no reducer is needed.
    """

    graph = StateGraph(WorkflowState)

    graph.add_node("parse", parse_input)
    graph.add_node("validate", validate_data)
    graph.add_node("context", build_context)
    graph.add_node("extract", extract_dataset)
    graph.add_node("select_test", select_test)
    graph.add_node("statistics", run_statistics)
    graph.add_node("verify", verify_results)
    graph.add_node("explain", explain_results)
    graph.add_node("report", generate_report)

    # Linear pipeline up to statistics
    graph.add_edge(START, "parse")
    graph.add_edge("parse", "validate")
    graph.add_edge("validate", "context")
    graph.add_edge("context", "extract")
    graph.add_edge("extract", "select_test")
    graph.add_edge("select_test", "statistics")

    # Parallel fan-out: statistics → verify AND statistics → explain
    graph.add_edge("statistics", "verify")
    graph.add_edge("statistics", "explain")

    # Both verify and explain fan into report
    graph.add_edge("verify", "report")
    graph.add_edge("explain", "report")

    graph.add_edge("report", END)

    return graph.compile()


# ==========================================================
# Singleton Workflow
# ==========================================================

workflow = build_workflow()
