"""
workflow.py

Central workflow orchestration for StatVerify AI.

The workflow is intentionally independent from Streamlit.

UI  ---> Workflow ---> Parser ---> Statistics ---> Reports ---> AI

The workflow communicates through a shared state object.
"""

from __future__ import annotations

from typing import Any, TypedDict

from langgraph.graph import END, START, StateGraph

from src.models import (
    AnalysisMode,
    AnalysisRequest,
    InputType,
    ReportData,
    StatisticalResult,
)
from src.parser import UniversalParser
from src.planner import AnalysisPlanner
from src.extractor import StatisticalDataExtractor
from src.statistics import StatisticalDecisionEngine, StatisticalEngine
from src.utils import logger
from src.validator import DataValidator


# ==========================================================
# Workflow State
# ==========================================================


class WorkflowState(TypedDict):
    """
    Shared workflow state.
    """

    request: Any

    selected_test: Any

    parsed_table: Any

    context: Any

    dataset: Any

    test_recommendation: Any

    statistical_result: Any

    # Only used in verification mode
    reported_result: Any

    verification_result: Any

    report: Any

    ai_response: Any

    # PDF generated by ReportEngine
    report_path: str | None

    error: str | None


# ==========================================================
# Orchestrator Components
# ==========================================================

parser = UniversalParser()

validator = DataValidator()

planner = AnalysisPlanner()

extractor = StatisticalDataExtractor()

decision_engine = StatisticalDecisionEngine()

statistics_engine = StatisticalEngine()

from src.verification import VerificationEngine
from src.ai import AIEngine
from src.reports import ReportEngine

verification_engine = VerificationEngine()

report_engine = ReportEngine()

ai_engine = AIEngine()


# ==========================================================
# Helpers
# ==========================================================


def has_error(state: WorkflowState) -> bool:
    """
    Stop executing workflow if any previous stage failed.
    """

    return state.get("error") is not None


# ==========================================================
# Workflow Nodes
# ==========================================================


def parse_input(state: WorkflowState) -> WorkflowState:
    """
    Parse uploaded input.
    """
    if has_error(state):
        return state

    try:
        logger.info("Running parser...")

        input_data = state.get("request") or "sample.csv"
        if isinstance(input_data, AnalysisRequest) and input_data.source_name:
            input_data = input_data.source_name
        elif hasattr(input_data, "source"):
            input_data = input_data.source

        state["parsed_table"] = parser.parse(input_data)
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def validate_data(state: WorkflowState) -> WorkflowState:
    """
    Validate parsed table.
    """
    if has_error(state):
        return state

    try:
        logger.info("Validating data...")

        table = state.get("parsed_table")
        if table is not None:
            validation = validator.validate(table)
            table.validation = validation
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def build_context(state: WorkflowState) -> WorkflowState:
    """
    Build statistical context.
    """
    if has_error(state):
        return state

    try:
        logger.info("Building analysis context...")

        table = state["parsed_table"]

        state["context"] = planner.build_context(table)
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def extract_dataset(state: WorkflowState) -> WorkflowState:
    """
    Extract statistical dataset from parsed table and context.
    """
    if has_error(state):
        return state

    try:
        logger.info("Extracting dataset...")

        if state.get("parsed_table") is not None and state.get("context") is not None:
            state["dataset"] = extractor.extract(
                state["parsed_table"],
                state["context"],
            )
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def select_test(state: WorkflowState) -> WorkflowState:
    """
    Select statistical test.

    If the user selected a test,
    use it.

    Otherwise,
    automatically recommend one.
    """
    if has_error(state):
        return state

    try:
        logger.info("Selecting statistical test...")

        selected = state.get("selected_test")

        # User selected a test explicitly
        if selected is not None:

            from src.models import TestRecommendation

            state["test_recommendation"] = TestRecommendation(
                test=selected,
                reason="User selected statistical test.",
                confidence=1.0,
            )

            return state

        # Automatic recommendation
        table = state.get("parsed_table")
        context = state.get("context")

        if table is not None:
            state["test_recommendation"] = decision_engine.recommend(
                table,
                context,
            )

    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def run_statistics(state: WorkflowState) -> WorkflowState:
    """
    Execute statistical analysis.
    """
    if has_error(state):
        return state

    try:
        logger.info("Running statistical engine...")

        dataset = state.get("dataset")
        recommendation = state.get("test_recommendation")

        if dataset is not None and recommendation is not None:
            state["statistical_result"] = statistics_engine.execute(
                dataset,
                recommendation,
            )
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def verify_results(state: WorkflowState) -> WorkflowState:
    """
    Compare reported and calculated statistics.
    """
    if has_error(state):
        return state

    logger.info("Running verification...")

    try:
        request = state.get("request")

        if (
            request is None
            or request.mode != AnalysisMode.VERIFICATION
        ):
            return state

        reported = state.get("reported_result")
        calculated = state.get("statistical_result")

        if reported is None or calculated is None:
            return state

        state["verification_result"] = (
            verification_engine.verify(
                reported,
                calculated,
            )
        )
    except Exception as error:
        logger.exception(error)
        state["error"] = str(error)

    return state


def explain_results(state: WorkflowState) -> WorkflowState:
    """
    Generate AI explanation.
    """
    if has_error(state):
        return state

    logger.info("Generating AI explanation...")

    try:

        result = state.get("statistical_result")

        if result is None:
            return state

        ai = ai_engine.explain(result)

        state["ai_response"] = ai

        report = state.get("report")

        if report is not None:
            report.ai = ai

    except Exception as error:

        logger.exception(error)

        state["error"] = str(error)

    return state


def generate_report(state: WorkflowState) -> WorkflowState:
    """
    Build report and generate PDF.
    """
    if has_error(state):
        return state

    logger.info("Generating report...")

    try:

        req = state.get("request")

        if not isinstance(req, AnalysisRequest):
            req = AnalysisRequest(
                mode=AnalysisMode.CALCULATION,
                input_type=InputType.CSV,
                source_name="sample.csv",
            )

        stat = state.get("statistical_result")

        if stat is None:
            stat = StatisticalResult(test_name="Unknown")

        report = ReportData(
            request=req,
            statistics=stat,
            verification=state.get("verification_result"),
            ai=state.get("ai_response"),
        )

        state["report"] = report

    except Exception as error:

        logger.exception(error)

        state["error"] = str(error)

    return state


# ==========================================================
# Build Workflow
# ==========================================================


def build_workflow():
    """
    Build LangGraph workflow.
    """

    graph = StateGraph(WorkflowState)

    graph.add_node("parse", parse_input)
    graph.add_node("validate", validate_data)
    graph.add_node("context", build_context)
    graph.add_node("extract", extract_dataset)
    graph.add_node("select_test", select_test)
    graph.add_node("statistics", run_statistics)
    graph.add_node("verify", verify_results)
    graph.add_node("explain", explain_results)
    graph.add_node("report", generate_report)

    graph.add_edge(START, "parse")
    graph.add_edge("parse", "validate")
    graph.add_edge("validate", "context")
    graph.add_edge("context", "extract")
    graph.add_edge("extract", "select_test")
    graph.add_edge("select_test", "statistics")
    graph.add_edge("statistics", "verify")
    graph.add_edge("verify", "explain")
    graph.add_edge("explain", "report")
    graph.add_edge("report", END)

    return graph.compile()


# ==========================================================
# Singleton Workflow
# ==========================================================

workflow = build_workflow()
